import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Financials.module.css";
import FinHeader from "../components/MiniCard";
import { FinInfo } from "../components/MiniCard";
import NavButton from "../components/NavButton";
import {
  AiOutlineAccountBook,
  AiOutlineCreditCard,
  AiOutlineUser,
  AiOutlineHome,
  AiOutlineTransaction,
  AiOutlineStar,
} from "react-icons/ai";

export default function Financials({ data }) {
  const [info, setInfo] = React.useState(data[data.length - 1]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.topNav}>
          <p>Logo</p>
          <div className={styles.right}>
            <p>Hi, {info.firstname}</p>
          </div>
        </div>
        <div className={styles.dashboard}>
          <nav className={styles.leftNav}>
            <NavButton
              title="Dashboard"
              page="/"
              icon={<AiOutlineHome size={28} />}
            />
            <NavButton
              title="Profile"
              page="/profile"
              icon={<AiOutlineUser size={28} />}
            />
            <NavButton
              title="Financials"
              page="/profile"
              icon={<AiOutlineAccountBook size={28} />}
            />
            <NavButton
              title="Make Payment"
              page="/profile"
              icon={<AiOutlineCreditCard size={28} />}
            />
          </nav>
          <div className={styles.content}>
            <p>Financial Information</p>
            <div className={styles.cardHolders}>
              <FinHeader />
              <FinInfo />
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Made with ❤️ by Debug Lab</footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch(
    `https://6133cf387859e700176a37b7.mockapi.io/api/info/info`
  );
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data },
  };
}
