import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Login.module.css";
import Button from "../components/Button";

export default function LogIn() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.box}>
          <h1>Log In</h1>
          <div className={styles.grid}>
            <input className={styles.input} placeholder="Email" type="email" />
            <input
              className={styles.input}
              placeholder="Password"
              type="password"
            />
            <Link href="/">
              <a>Log In</a>
            </Link>
            <Button title="Log In" />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Made with ❤️ by Debug Lab</footer>
    </div>
  );
}
