import Head from "next/head";
import React from "react";
import Modal from "react-modal";
import styles from "../styles/Profile.module.css";
import InfoContent from "../components/InfoContent";
import InfoProfile from "../components/infoProfile";
import EditModal from "../components/EditModal";
import Button from "../components/Button";

const customStyles = {
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
  },
};

export default function Home({ data }) {
  let subtitle;
  const [modalIsOpen, setIsOpen] = React.useState(false);

  function openModal() {
    setIsOpen(true);
    console.log(data);
  }

  function afterOpenModal() {
    // references are now sync'd and can be accessed.
    subtitle.style.color = "#f00";
  }

  function closeModal() {
    setIsOpen(false);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.topNav}>
          <div>
            {/* <button onClick={openModal}>Open Modal</button> */}
            <Modal
              isOpen={modalIsOpen}
              onAfterOpen={afterOpenModal}
              onRequestClose={closeModal}
              style={customStyles}
              contentLabel="Example Modal"
            >
              <h3 ref={(_subtitle) => (subtitle = _subtitle)}>
                Edit Personal Information
              </h3>
              {/* <EditModal /> */}
              <Button title="Save" width="100px" />
            </Modal>
          </div>
          <p style={{ fontSize: "small" }}>Logo</p>
          <div className={styles.right}>
            <p style={{ fontSize: "small" }}>Ahmed Ahmed</p>
          </div>
        </div>

        <div className={styles.dashboard}>
          <nav className={styles.leftNav}>
            <p>Dashboard</p>
            <p>Profile</p>
            <p>Financials</p>
            <p>Make Payment</p>
          </nav>
          <div className={styles.content}>
            <p>Profile</p>
            <div className={styles.contentMain}>
              <div className={styles.profile}>
                <div className={styles.profileInfo}>
                  <div className={styles.photo}></div>
                  <InfoContent type="Grade" value="Member" />
                  <InfoContent type="Status" value="Active" />
                </div>
                <div className={styles.profileInfo}>
                  <p style={{ fontWeight: "bold" }}>About Me</p>
                  <InfoContent
                    type="Education"
                    value="University of Portsmouth"
                  />
                  <InfoContent type="Location" value="FCT" />
                  <InfoContent type="Region" value="Abuja" />
                </div>
              </div>
              <div className={styles.info}>
                <div className={styles.header}>
                  <p style={{ fontWeight: "bold", padding: "10px" }}>
                    Personal Infomation
                  </p>
                  <p
                    style={{ color: "rgb(49, 138, 255)", padding: "10px" }}
                    onClick={openModal}
                  >
                    Edit
                  </p>
                </div>
                <div>
                  <InfoProfile type="Registration No." value="004602/2015" />
                  <InfoProfile type="Full Name." value="Ahmed Ahmed" />
                  <InfoProfile type="Grade" value="Member" />
                  <InfoProfile
                    type="Contact Address"
                    value="9, AUDU OGBEH STREET,JABI, ABUJA,JABI ABUJA"
                  />
                  <InfoProfile type="Phone No." value="080xxxxxxxx" />
                  <InfoProfile type="E-Mail" value="a.ahmed@ptdf.gov.ng" />
                  <InfoProfile type="Employer's Name" value="PTDF ABUJA" />
                  <InfoProfile
                    type="Employer's Address"
                    value="PTDF TOWER, MEMORIAL CLOSE,OPP. SHEHU YARADUA CENTRE, ABUJA"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Made with ❤️ by Debug Lab</footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch(
    `https://6133cf387859e700176a37b7.mockapi.io/api/info/info`
  );
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data },
  };
}
