import Head from "next/head";
import { Formik, Field, Form } from "formik";
import "react-datepicker/dist/react-datepicker.css";
import styles from "../styles/Register.module.css";
import Input from "../components/Input";
import Select from "../components/Select";
import Calender from "../components/DatePicker";
import Button from "../components/Button";

export default function Register() {
  const registerUser = async (data) => {
    const res = await fetch(
      "https://6133cf387859e700176a37b7.mockapi.io/api/info/info",
      {
        body: JSON.stringify(data),
        headers: {
          "Content-Type": "application/json",
        },
        method: "POST",
      }
    );
    console.log(res, "response");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.header}>Register</p>
        <Formik
          initialValues={{
            pin: "",
            title: "",
            firstname: "",
            lastname: "",
            middlename: "",
            bloodgroup: "",
            sex: "",
            sog: "",
            home_address: "",
            employer: "",
            office_address: "",
            phone: "",
            email: "",
            vehicle_make: "",
            vehicle_reg_no: "",
            driving_license_no: "",
            nok: "",
            nok_phone: "",
            doe: new Date(),
            dob: new Date(),
            ndl_expiration_date: new Date(),
            regalia: "",
            idcard: "",
          }}
          onSubmit={async (values) => {
            await registerUser(values);
            await new Promise((r) => setTimeout(r, 500));
            alert(JSON.stringify(values, null, 2));
          }}
        >
          <Form>
            <div className={styles.grid}>
              <Input
                title="Pin"
                htmlFor="pin"
                id="pin"
                name="pin"
                placeholder=""
              />
              <Input
                title="Title"
                htmlFor="title"
                id="title"
                name="title"
                placeholder=""
              />
            </div>
            <div className={styles.grid}>
              <Input
                title="First Name"
                htmlFor="firstname"
                id="firstname"
                name="firstname"
                placeholder=""
              />
              <Input
                title="Last Name"
                htmlFor="lastname"
                id="lastname"
                name="lastname"
                placeholder=""
              />
              <Input
                title="Middle Name"
                htmlFor="middlename"
                id="middlename"
                name="middlename"
                placeholder=""
              />
            </div>
            <div className={styles.grid}>
              <Calender name="dob" title="Date of Birth" />
              <Input
                title="Sex"
                htmlFor="sex"
                id="sex"
                name="sex"
                placeholder=""
              />
              <Input
                title="Blood Group"
                htmlFor="bloodgroup"
                id="bloodgroup"
                name="bloodgroup"
                placeholder=""
              />
            </div>
            <div className={styles.grid}>
              <Select name="sog" />
              <Input
                title="Home Address"
                htmlFor="home_address"
                id="home_address"
                name="home_address"
                placeholder=""
              />
            </div>
            <div className={styles.grid}>
              <Input
                title="Employer"
                htmlFor="employer"
                id="employer"
                name="employer"
                placeholder=""
              />
              <Input
                title="Office Address"
                htmlFor="office_address"
                id="office_address"
                name="office_address"
                placeholder=""
              />
            </div>
            <div className={styles.grid}>
              <Input
                title="Phone No"
                htmlFor="phone"
                id="phone"
                name="phone"
                placeholder=""
                type="tel"
              />
              <Input
                title="Email"
                htmlFor="email"
                id="email"
                name="email"
                placeholder=""
                type="email"
              />
            </div>
            <div className={styles.grid}>
              <Input
                title="Vehicle Make/Model"
                htmlFor="vehicle_make"
                id="vehicle_make"
                name="vehicle_make"
                placeholder=""
              />
              <Input
                title="Vehicle Reg No"
                htmlFor="vehicle_reg_no"
                id="vehicle_reg_no"
                name="vehicle_reg_no"
                placeholder=""
              />
            </div>
            <div className={styles.grid}>
              <Input
                title="Driving License No"
                htmlFor="driving_license_no"
                id="driving_license_no"
                name="driving_license_no"
                placeholder=""
              />
              {/* <Calender title="NDL Expiration Date" /> */}
              <Calender
                name="ndl_expiration_date"
                title="NDL Expiration Date"
              />
            </div>
            <div className={styles.grid}>
              <Input
                title="Next of Kin"
                htmlFor="nok"
                id="nok"
                name="nok"
                placeholder=""
              />
              <Input
                title="Phone No"
                htmlFor="nok_phone"
                id="nok_phone"
                name="nok_phone"
                placeholder=""
                type="tel"
              />
            </div>
            <div className={styles.grid}>
              <Calender name="doe" title="Date of Enlistment" />
            </div>
            <div className={styles.grid}>
              <div style={{ margin: "10px" }}>
                <div id="my-radio-group">Regalia</div>
                <div role="group" aria-labelledby="my-radio-group">
                  <label>
                    <Field type="radio" name="regalia" value="No" />
                    No
                  </label>
                  <label>
                    <Field type="radio" name="regalia" value="Yes" />
                    Yes
                  </label>
                  {/* <div>Picked: {values.picked}</div> */}
                </div>
              </div>
            </div>
            <div className={styles.grid}>
              <div style={{ margin: "10px" }}>
                <div id="my-radio-group">I.D</div>
                <div role="group" aria-labelledby="my-radio-group">
                  <label>
                    <Field type="radio" name="idcard" value="No" />
                    No
                  </label>
                  <label>
                    <Field type="radio" name="idcard" value="Yes" />
                    Yes
                  </label>
                  {/* <div>Picked: {values.picked}</div> */}
                </div>
              </div>
            </div>
            <Button
              title="Register"
              type="submit"
              width="100px"
              onClick={() => console.log("SALIM")}
            />
          </Form>
        </Formik>
      </main>

      <footer className={styles.footer}>Made with ❤️ by Debug Lab</footer>
    </div>
  );
}
