import Head from "next/head";
import styles from "../styles/Register.module.css";
import Input from "../components/Input";
import Select from "../components/Select";
import Calender from "../components/DatePicker";

export default function Register() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.header}>Register</p>
        <div className={styles.grid}>
          <Input title="Pin" />
          <Input title="Title" />
        </div>
        <div className={styles.grid}>
          <Input title="Surname" />
          <Input title="First Name" />
          <Input title="Middle Name" />
        </div>
        <div className={styles.grid}>
          <Calender title="Date of Birth" />
          <Input title="Sex" />
          <Input title="Blood Group" />
        </div>
        <div className={styles.grid}>
          <Select />
          <Input title="Home Address" />
        </div>
        <div className={styles.grid}>
          <Input title="Employer" />
          <Input title="Office Address" />
        </div>
        <div className={styles.grid}>
          <Input title="Phone No" />
          <Input title="Email" />
        </div>
        <div className={styles.grid}>
          <Input title="Vehicle Make/Model" />
          <Input title="Vehicle Reg No." />
        </div>
        <div className={styles.grid}>
          <Input title="Driving License No." />
          <Calender title="NDL Expiration Date" />
        </div>
        <div className={styles.grid}>
          <Input title="Next of Kin" />
          <Input title="Phone No." />
        </div>
        <div className={styles.grid}>
          <Input title="Date of Enlistment" />
        </div>
        <div className={styles.grid}>
          <div style={{ margin: "10px" }}>
            <span>Regalia</span>
            <input
              type="radio"
              id="contactChoice1"
              name="contact"
              value="Yes"
            />
            <label for="contactChoice1">Yes</label>
            <input type="radio" id="contactChoice1" name="contact" value="No" />
            <label for="contactChoice1">No</label>
          </div>
        </div>
        <div className={styles.grid}>
          <div style={{ margin: "10px" }}>
            <span>I.D</span>
            <input
              type="radio"
              id="contactChoice1"
              name="contact"
              value="Yes"
            />
            <label for="contactChoice1">Yes</label>
            <input type="radio" id="contactChoice1" name="contact" value="No" />
            <label for="contactChoice1">No</label>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Made with ❤️ by Debug Lab</footer>
    </div>
  );
}
